version: '3.3'

services:
        app:
                container_name: apigateway
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                ports:
                        - "8000:8000"
