server:
  port: 8000
  ssl:
    enabled: true
    key-alias: ushopkeystore
    key-store: classpath:ushopkeystore.p12
    key-store-password: 12345678
    key-password: 12345678
    key-store-type: PKCS12

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
        connect-timeout: 2000
        response-timeout: 2s
      routes:
        - id: productservice
          uri: lb://productservice
          predicates:
            - Path=/product/**
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: searchservice
          uri: lb://searchservice
          predicates:
            - Path=/search/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allow-credentials: true
            allowed-headers:
              - x-requested-with
              - content-type
            allowed-methods:
              - POST
              - GET
              - PUT
              - DELETE
