server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:64421 #forwarding할 주소, http://localhost:8080/product 로 들어오면 http://localhost:64421로 포워딩 됨
          predicates:
            - Path=/product/**
        - id: order-service
          uri: http://localhost:54421
          predicates:
            - Path=/order/**
