server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone:  http://a9630be5aa11c4d0a8ae29e80ddf7437-1705600513.ap-northeast-2.elb.amazonaws.com:8761/eureka
    instance:
      instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 2s
      routes:
        - id: productservice
          uri: http://10.100.83.140:64421/
          predicates:
            - Path=/product/**
        - id: orderservice
          uri:  http://10.100.90.70:54421/
          predicates:
            - Path=/order/**
        - id: searchservice
          uri: http://a9630be5aa11c4d0a8ae29e80ddf7437-1705600513.ap-northeast-2.elb.amazonaws.com:44421/
          predicates:
            - Path=/search/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
            allow-credentials: true
            allowed-headers:
              - x-requested-with
              - content-type
            allowed-methods:
              - POST
              - GET
              - PUT
              - DELETE
